### ISSUE TITLE
Analyze overlapped P2P memory transfer and computing

### ISSUE THREAD

**Issue by andreaskoepf** [cuda-mode/ring-attention#1]
Create an ipynb to analyze in PyTorch the peer-to-peer (between two GPUs) memory transfer and computing in parallel. Dummy computation could for example be some larger matmuls in a loop. Create notebooks folder and place the file there.

Goal should be to demonstrate that memory transfer and computation can run (to some degree) overlapped.

- Old nvidia blog post: [How to Overlap Data Transfers in CUDA C/C++](https://pytorch.org/docs/stable/notes/cuda.html#cuda-streams)
- cuda steams in pytorch, see [CUDA streams](https://pytorch.org/docs/stable/notes/cuda.html#cuda-streams)
- Slides: [Data Transfer and CUDA Streams](https://people.cs.vt.edu/yongcao/teaching/cs5234/spring2013/slides/Lecture9.pdf)
- Slides: [CUDA STREAMS BEST PRACTICES AND COMMON PITFALLS](https://on-demand.gputechconf.com/gtc/2014/presentations/S4158-cuda-streams-best-practices-common-pitfalls.pdf)

Quote from the ring-attention paper:
"If the computation time exceeds the time required for transferring key-value blocks, this results in no additional communication cost. This overlapping mechanism applies to both forward and backward passes of our approach since the same operations and techniques can be used"

**Comment by eternalops** [comment]
first one's link: https://developer.nvidia.com/blog/how-overlap-data-transfers-cuda-cc/

**Comment by andreaskoepf** [comment]
https://github.com/zhuzilin/ring-flash-attention/pull/9
