### ISSUE TITLE
Extend educational naive flash-attn impl to allow partial kv-block processing (create naive ring-attn)

### ISSUE THREAD

**Issue by andreaskoepf** [cuda-mode/ring-attention#4]
Extend the naive [flash-attn notebook](https://colab.research.google.com/drive/1X-x6PCRydNY9LZBPLA0DZh3Tj2Dyz60M?usp=sharingy) to allow block-wise processing of only a fraction of the blocks at a time, i.e. pass in and out state required to continue updating the outputs for the current queries (e.g. store block max, current sum etc).

With new function create a little test that shows that all values of splitted processing are "allclose()" to the same computation as classic dot product attention (see `naive_attn()` in the notebook linked above).

Store the generated ipynb file in the notebooks folder of this repo.

**Comment by lancerts** [comment]
Did a more basic implementation of flash attn forward pass based on the paper with annotations. 
The [notebook](https://github.com/lancerts/Algo-From-Scratch/blob/main/flash_attn/naive_flash.ipynb) for educational purpose.

**Comment by lancerts** [comment]
Added an incremental [version](https://github.com/lancerts/Algo-From-Scratch/blob/main/flash_attn/naive_flash.ipynb) on cell 5 and below along k and v block.
